from __future__ import annotations

import uuid
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from panel_core.extensions import db
from panel_core.models import Payment, SystemSetting, Tariff, TariffItem, UserTariffAccess
from panel_core.services import billing


@pytest.fixture
def configured_yookassa(app):
    with app.app_context():
        db.session.add_all(
            [
                SystemSetting(key="yookassa_shop_id", value="test-shop"),
                SystemSetting(key="yookassa_secret_key", value="test_secret"),
                SystemSetting(key="yookassa_return_url", value="https://t.me/itg_bot"),
            ]
        )
        db.session.commit()
    yield


@pytest.fixture
def public_tariff(app, configured_yookassa):
    with app.app_context():
        t = Tariff(
            name="Standard 30d",
            price_rub=150,
            period_days=30,
            visibility="public",
            enabled=True,
            is_trial=False,
        )
        t.items = [TariffItem(inbound_tag="vless-de", traffic_gb=0)]
        db.session.add(t)
        db.session.commit()
        yield t.id


def _mock_yk_payment(payment_id="yk-test-001", url="https://yookassa.test/pay/abc"):
    return SimpleNamespace(
        id=payment_id,
        confirmation=SimpleNamespace(confirmation_url=url),
    )


def test_create_checkout_inserts_pending_payment_and_returns_url(app, public_tariff):
    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.return_value = _mock_yk_payment()
        result = billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")

    assert result["confirmation_url"] == "https://yookassa.test/pay/abc"
    assert result["yookassa_id"] == "yk-test-001"
    assert result["amount_rub"] == 150
    with app.app_context():
        p = Payment.query.filter_by(yookassa_id="yk-test-001").one()
        assert p.status == "pending"
        assert p.telegram_id == 42
        assert p.tariff_id == public_tariff
        assert p.amount_rub == 150
        assert p.tariff_snapshot["name"] == "Standard 30d"
        assert p.tariff_snapshot["price_rub"] == 150
        assert p.tariff_snapshot["items"] == [
            {"inbound_tag": "vless-de", "traffic_gb": 0, "panel_id": None},
        ]


def test_create_checkout_omits_receipt_for_self_employed(app, public_tariff):

    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.return_value = _mock_yk_payment()
        billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")

    payload, idempotence_key = mock_create.call_args.args
    assert idempotence_key
    assert "receipt" not in payload, "receipt should not be present — auto-generated by YooKassa"


def test_create_checkout_includes_metadata(app, public_tariff):
    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.return_value = _mock_yk_payment()
        result = billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")

    payload, _ = mock_create.call_args.args
    md = payload["metadata"]
    assert md["telegram_id"] == 42
    assert md["tariff_id"] == public_tariff
    assert md["payment_db_id"] == result["payment_id"]


def test_create_checkout_rejects_disabled_tariff(app, public_tariff):
    with app.app_context():
        db.session.get(Tariff, public_tariff).enabled = False
        db.session.commit()
        with pytest.raises(ValueError, match="tariff_not_available"):
            billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")


def test_create_checkout_rejects_archived_tariff(app, public_tariff):
    with app.app_context():
        db.session.get(Tariff, public_tariff).visibility = "archived"
        db.session.commit()
        with pytest.raises(ValueError, match="tariff_not_available"):
            billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")


def test_create_checkout_rejects_trial_tariff(app, public_tariff):
    with app.app_context():
        db.session.get(Tariff, public_tariff).is_trial = True
        db.session.commit()
        with pytest.raises(ValueError, match="tariff_not_available"):
            billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")


def test_create_checkout_private_tariff_requires_grant(app, configured_yookassa):
    with app.app_context():
        t = Tariff(
            name="VIP",
            price_rub=999,
            period_days=30,
            visibility="private",
            enabled=True,
            is_trial=False,
        )
        t.items = [TariffItem(inbound_tag="vless-de", traffic_gb=0)]
        db.session.add(t)
        db.session.commit()
        tariff_id = t.id

    with app.app_context(), pytest.raises(ValueError, match="tariff_not_available"):
        billing.create_checkout(telegram_id=42, tariff_id=tariff_id, lang="ru")

    with app.app_context():
        db.session.add(
            UserTariffAccess(
                telegram_id=42,
                tariff_id=tariff_id,
                billing="paid",
            )
        )
        db.session.commit()
    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.return_value = _mock_yk_payment(payment_id="yk-vip-001")
        result = billing.create_checkout(telegram_id=42, tariff_id=tariff_id, lang="ru")
    assert result["yookassa_id"] == "yk-vip-001"


def test_create_checkout_raises_when_yookassa_not_configured(app):
    with app.app_context():
        t = Tariff(
            name="X",
            price_rub=100,
            period_days=30,
            visibility="public",
            enabled=True,
            is_trial=False,
        )
        t.items = [TariffItem(inbound_tag="vless-de", traffic_gb=0)]
        db.session.add(t)
        db.session.commit()
        with pytest.raises(ValueError, match="yookassa_not_configured"):
            billing.create_checkout(telegram_id=42, tariff_id=t.id, lang="ru")


def test_create_checkout_commits_payment_before_yookassa_call(app, public_tariff):

    from sqlalchemy import event as _event
    from sqlalchemy.orm import Session as _SQLASession

    commits_count = [0]
    yk_call_commit_idx: list[int] = []

    def _on_commit(_session):
        commits_count[0] += 1

    def _on_yk(*_a, **_kw):
        yk_call_commit_idx.append(commits_count[0])
        return _mock_yk_payment()

    with app.app_context():
        _event.listen(_SQLASession, "after_commit", _on_commit)
        try:
            with patch("panel_core.services.billing.yookassa.Payment.create", side_effect=_on_yk):
                billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")
        finally:
            _event.remove(_SQLASession, "after_commit", _on_commit)

    assert len(yk_call_commit_idx) == 1, "yookassa.Payment.create should be invoked exactly once"
    assert yk_call_commit_idx[0] >= 1, (
        f"yookassa.Payment.create was called after {yk_call_commit_idx[0]} commits — "
        f"the Payment INSERT is still inside an open SQLite write transaction. "
        f"Holds the writer lock across the HTTPS call (up to 16s with retry)."
    )


from panel_core.services import provisioning  # noqa: E402,F401


def _make_payment(app, telegram_id, tariff_id, status="pending"):
    with app.app_context():
        p = Payment(
            yookassa_id=f"yk-{uuid.uuid4().hex[:8]}",
            telegram_id=telegram_id,
            tariff_id=tariff_id,
            tariff_snapshot={"name": "x", "price_rub": 100, "period_days": 30, "items": []},
            amount_rub=100,
            status=status,
            metadata_json={"lang": "ru"},
        )
        db.session.add(p)
        db.session.commit()
        return p.id


def test_apply_payment_marks_succeeded_and_calls_provisioning(app, public_tariff):
    pid = _make_payment(app, telegram_id=42, tariff_id=public_tariff)
    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as mock_provision,
        patch("panel_core.services.billing.bot_events.publish") as mock_publish,
    ):
        mock_provision.return_value = {
            "clients": [{"email": "tg42@vless-de"}],
            "expires_at_ms": 9999999999000,
            "source": "yookassa",
        }
        billing.apply_payment(db.session.get(Payment, pid))

    with app.app_context():
        p = db.session.get(Payment, pid)
        assert p.status == "succeeded"
        assert p.paid_at is not None
    mock_provision.assert_called_once()
    args, kwargs = mock_provision.call_args
    assert kwargs["source"] == "yookassa"
    mock_publish.assert_called_once()
    event_type, tg_id, payload = mock_publish.call_args.args
    assert event_type == "payment_succeeded"
    assert tg_id == 42
    assert payload["payment_id"] == pid
    assert payload["expires_at_ms"] == 9999999999000


def test_apply_payment_is_idempotent(app, public_tariff):
    pid = _make_payment(app, telegram_id=42, tariff_id=public_tariff, status="succeeded")
    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as mock_provision,
        patch("panel_core.services.billing.bot_events.publish") as mock_publish,
    ):
        billing.apply_payment(db.session.get(Payment, pid))
    mock_provision.assert_not_called()
    mock_publish.assert_not_called()


def test_apply_payment_marks_failed_when_tariff_archived_with_no_items(app, public_tariff):
    pid = _make_payment(app, telegram_id=42, tariff_id=public_tariff)
    with app.app_context():
        t = db.session.get(Tariff, public_tariff)
        for item in list(t.items):
            db.session.delete(item)
        db.session.commit()
    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as mock_provision,
        patch("panel_core.services.billing.bot_events.publish") as mock_publish,
    ):
        billing.apply_payment(db.session.get(Payment, pid))

    with app.app_context():
        assert db.session.get(Payment, pid).status == "failed"
    mock_provision.assert_not_called()
    mock_publish.assert_called_once()
    assert mock_publish.call_args.args[0] == "payment_failed"


def test_apply_payment_marks_failed_when_tariff_archived_between_checkout_and_webhook(app, public_tariff):

    pid = _make_payment(app, telegram_id=42, tariff_id=public_tariff)
    with app.app_context():
        t = db.session.get(Tariff, public_tariff)
        t.visibility = "archived"
        db.session.commit()
    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as mock_provision,
        patch("panel_core.services.billing.bot_events.publish") as mock_publish,
    ):
        billing.apply_payment(db.session.get(Payment, pid))

    with app.app_context():
        assert db.session.get(Payment, pid).status == "failed"
    mock_provision.assert_not_called()
    mock_publish.assert_called_once()
    event_type, tg_id, payload = mock_publish.call_args.args
    assert event_type == "payment_failed"
    assert tg_id == 42
    assert payload["reason"] == "tariff_unavailable"


def test_apply_payment_skips_when_row_no_longer_pending(app, public_tariff):

    from sqlalchemy import update as _update

    pid = _make_payment(app, telegram_id=42, tariff_id=public_tariff)
    with app.app_context():
        db.session.execute(_update(Payment).where(Payment.id == pid).values(status="processing"))
        db.session.commit()

    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as mock_provision,
        patch("panel_core.services.billing.bot_events.publish") as mock_publish,
    ):
        billing.apply_payment(db.session.get(Payment, pid))

    mock_provision.assert_not_called()
    mock_publish.assert_not_called()


def test_apply_payment_marks_failed_when_private_tariff_lost_grant(app, public_tariff):

    pid = _make_payment(app, telegram_id=42, tariff_id=public_tariff)
    with app.app_context():
        t = db.session.get(Tariff, public_tariff)
        t.visibility = "private"
        db.session.commit()
    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as mock_provision,
        patch("panel_core.services.billing.bot_events.publish") as mock_publish,
    ):
        billing.apply_payment(db.session.get(Payment, pid))

    with app.app_context():
        assert db.session.get(Payment, pid).status == "failed"
    mock_provision.assert_not_called()
    assert mock_publish.call_args.args[0] == "payment_failed"
