from __future__ import annotations

import uuid
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from panel_core.extensions import db
from panel_core.models import BotEvent, Payment, SystemSetting, Tariff, TariffItem, UserTariffAccess, Inbound
from panel_core.services import billing


@pytest.fixture(autouse=True)
def available_inbounds(app):
    with app.app_context():
        db.session.add(Inbound(tag="vless-de", protocol="vless", port=14443, stream_settings="{}"))
        db.session.commit()


@pytest.fixture
def configured_yookassa(app):
    with app.app_context():
        db.session.add_all(
            [
                SystemSetting(key="yookassa_shop_id", value="test-shop"),
                SystemSetting(key="yookassa_secret_key", value="test_secret"),
                SystemSetting(key="yookassa_return_url", value="https://t.me/itg_bot"),
            ]
        )
        db.session.commit()
    yield


@pytest.fixture
def public_tariff(app, configured_yookassa):
    with app.app_context():
        t = Tariff(
            name="Standard 30d",
            price_rub=150,
            period_days=30,
            visibility="public",
            enabled=True,
            is_trial=False,
        )
        t.items = [TariffItem(inbound_tag="vless-de", traffic_gb=0)]
        db.session.add(t)
        db.session.commit()
        yield t.id


def _mock_yk_payment(payload, key=None, payment_id="yk-test-001", url="https://yookassa.test/pay/abc"):
    return SimpleNamespace(
        id=payment_id,
        amount=SimpleNamespace(**payload["amount"]),
        metadata=payload["metadata"],
        confirmation=SimpleNamespace(confirmation_url=url),
    )


def test_create_checkout_inserts_pending_payment_and_returns_url(app, public_tariff):
    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.side_effect = _mock_yk_payment
        result = billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")

    assert result["confirmation_url"] == "https://yookassa.test/pay/abc"
    assert result["yookassa_id"] == "yk-test-001"
    assert result["amount_rub"] == 150
    with app.app_context():
        p = Payment.query.filter_by(yookassa_id="yk-test-001").one()
        assert p.status == "pending"
        assert p.telegram_id == 42
        assert p.tariff_id == public_tariff
        assert p.amount_rub == 150
        assert p.tariff_snapshot["name"] == "Standard 30d"
        assert p.tariff_snapshot["price_rub"] == 150
        assert p.tariff_snapshot["items"] == [
            {"inbound_tag": "vless-de", "traffic_gb": 0, "panel_id": None},
        ]


def test_create_checkout_omits_receipt_for_self_employed(app, public_tariff):

    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.side_effect = _mock_yk_payment
        billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")

    payload, idempotence_key = mock_create.call_args.args
    assert idempotence_key
    assert "receipt" not in payload, "receipt should not be present — auto-generated by YooKassa"


def test_create_checkout_includes_metadata(app, public_tariff):
    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.side_effect = _mock_yk_payment
        result = billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")

    payload, _ = mock_create.call_args.args
    md = payload["metadata"]
    assert md["telegram_id"] == 42
    assert md["tariff_id"] == public_tariff
    assert md["payment_db_id"] == result["payment_id"]


def test_create_checkout_rejects_disabled_tariff(app, public_tariff):
    with app.app_context():
        db.session.get(Tariff, public_tariff).enabled = False
        db.session.commit()
        with pytest.raises(ValueError, match="tariff_not_available"):
            billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")


def test_create_checkout_rejects_archived_tariff(app, public_tariff):
    with app.app_context():
        db.session.get(Tariff, public_tariff).visibility = "archived"
        db.session.commit()
        with pytest.raises(ValueError, match="tariff_not_available"):
            billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")


def test_create_checkout_rejects_trial_tariff(app, public_tariff):
    with app.app_context():
        db.session.get(Tariff, public_tariff).is_trial = True
        db.session.commit()
        with pytest.raises(ValueError, match="tariff_not_available"):
            billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")


def test_create_checkout_private_tariff_requires_grant(app, configured_yookassa):
    with app.app_context():
        t = Tariff(
            name="VIP",
            price_rub=999,
            period_days=30,
            visibility="private",
            enabled=True,
            is_trial=False,
        )
        t.items = [TariffItem(inbound_tag="vless-de", traffic_gb=0)]
        db.session.add(t)
        db.session.commit()
        tariff_id = t.id

    with app.app_context(), pytest.raises(ValueError, match="tariff_not_available"):
        billing.create_checkout(telegram_id=42, tariff_id=tariff_id, lang="ru")

    with app.app_context():
        db.session.add(
            UserTariffAccess(
                telegram_id=42,
                tariff_id=tariff_id,
                billing="paid",
            )
        )
        db.session.commit()
    with app.app_context(), patch("panel_core.services.billing.yookassa.Payment.create") as mock_create:
        mock_create.side_effect = lambda payload, key: _mock_yk_payment(payload, key, payment_id="yk-vip-001")
        result = billing.create_checkout(telegram_id=42, tariff_id=tariff_id, lang="ru")
    assert result["yookassa_id"] == "yk-vip-001"


def test_create_checkout_raises_when_yookassa_not_configured(app):
    with app.app_context():
        t = Tariff(
            name="X",
            price_rub=100,
            period_days=30,
            visibility="public",
            enabled=True,
            is_trial=False,
        )
        t.items = [TariffItem(inbound_tag="vless-de", traffic_gb=0)]
        db.session.add(t)
        db.session.commit()
        with pytest.raises(ValueError, match="yookassa_not_configured"):
            billing.create_checkout(telegram_id=42, tariff_id=t.id, lang="ru")


def test_create_checkout_commits_payment_before_yookassa_call(app, public_tariff):

    from sqlalchemy import event as _event
    from sqlalchemy.orm import Session as _SQLASession

    commits_count = [0]
    yk_call_commit_idx: list[int] = []

    def _on_commit(_session):
        commits_count[0] += 1

    def _on_yk(*_a, **_kw):
        yk_call_commit_idx.append(commits_count[0])
        return _mock_yk_payment(*_a, **_kw)

    with app.app_context():
        _event.listen(_SQLASession, "after_commit", _on_commit)
        try:
            with patch("panel_core.services.billing.yookassa.Payment.create", side_effect=_on_yk):
                billing.create_checkout(telegram_id=42, tariff_id=public_tariff, lang="ru")
        finally:
            _event.remove(_SQLASession, "after_commit", _on_commit)

    assert len(yk_call_commit_idx) == 1, "yookassa.Payment.create should be invoked exactly once"
    assert yk_call_commit_idx[0] >= 1, (
        f"yookassa.Payment.create was called after {yk_call_commit_idx[0]} commits — "
        f"the Payment INSERT is still inside an open SQLite write transaction. "
        f"Holds the writer lock across the HTTPS call (up to 16s with retry)."
    )


def _make_payment(app, telegram_id, tariff_id, status="pending"):
    with app.app_context():
        p = Payment(
            yookassa_id=f"yk-{uuid.uuid4().hex[:8]}",
            telegram_id=telegram_id,
            tariff_id=tariff_id,
            tariff_snapshot={
                "name": "Purchased",
                "price_rub": 100,
                "period_days": 30,
                "items": [{"inbound_tag": "vless-de", "traffic_gb": 0, "panel_id": None}],
            },
            amount_rub=100,
            status=status,
            metadata_json={"lang": "ru"},
            fulfillment_status="succeeded" if status == "succeeded" else "pending",
        )
        db.session.add(p)
        db.session.commit()
        return p.id


def test_apply_payment_marks_succeeded_and_stores_event(app, public_tariff):
    pid = _make_payment(app, 42, public_tariff)
    with (
        app.app_context(),
        patch(
            "panel_core.services.billing.provisioning.apply_tariff_for_user",
            return_value={"expires_at_ms": 9999999999000},
        ) as provision,
    ):
        billing.apply_payment(db.session.get(Payment, pid))
        payment = db.session.get(Payment, pid)
        assert payment.status == "succeeded"
        assert payment.provider_status == "succeeded"
        assert payment.paid_at is not None
        event = BotEvent.query.filter_by(type="payment_succeeded").one()
        assert event.telegram_id == 42
        assert event.payload["payment_id"] == pid
        assert event.payload["expires_at_ms"] == 9999999999000
        assert provision.call_args.kwargs["source"] == "yookassa"


def test_apply_payment_is_idempotent(app, public_tariff):
    pid = _make_payment(app, 42, public_tariff, "succeeded")
    with app.app_context(), patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as provision:
        billing.apply_payment(db.session.get(Payment, pid))
        provision.assert_not_called()
        assert BotEvent.query.count() == 0


@pytest.mark.parametrize("change", ["remove_items", "archive", "private_without_grant"])
def test_apply_payment_honors_purchase_after_catalogue_changes(app, public_tariff, change):
    pid = _make_payment(app, 42, public_tariff)
    with app.app_context():
        tariff = db.session.get(Tariff, public_tariff)
        if change == "remove_items":
            tariff.items.clear()
        else:
            tariff.visibility = "archived" if change == "archive" else "private"
        db.session.commit()
        with patch(
            "panel_core.services.billing.provisioning.apply_tariff_for_user", return_value={"expires_at_ms": 123}
        ) as provision:
            billing.apply_payment(db.session.get(Payment, pid))
        assert db.session.get(Payment, pid).fulfillment_status == "succeeded"
        assert provision.call_args.kwargs["tariff"].name == "Purchased"
        assert provision.call_args.kwargs["tariff"].items[0].inbound_tag == "vless-de"
        assert BotEvent.query.filter_by(type="payment_failed").count() == 0


def test_apply_payment_skips_when_another_owner_holds_lease(app, public_tariff):
    pid = _make_payment(app, 42, public_tariff)
    with app.app_context():
        p = db.session.get(Payment, pid)
        p.status = "processing"
        p.fulfillment_status = "processing"
        p.processing_owner = "another-owner"
        p.processing_version = 4
        db.session.commit()
        with patch("panel_core.services.billing.provisioning.apply_tariff_for_user") as provision:
            billing.apply_payment(p)
        provision.assert_not_called()
        assert BotEvent.query.count() == 0
        assert p.processing_owner == "another-owner"


@pytest.mark.parametrize(
    "error", [RuntimeError("node unreachable"), billing.provisioning.LocalXrayUnavailable("no local xray on this role")]
)
def test_paid_delivery_failure_remains_an_explicit_recoverable_debt(app, public_tariff, error):
    pid = _make_payment(app, 42, public_tariff)
    with (
        app.app_context(),
        patch("panel_core.services.billing.provisioning.apply_tariff_for_user", side_effect=error),
        pytest.raises(type(error)),
    ):
        billing.apply_payment(db.session.get(Payment, pid))
    with app.app_context():
        p = db.session.get(Payment, pid)
        assert p.status == "pending"
        assert p.provider_status == "succeeded"
        assert p.fulfillment_status == "retry"
        assert p.fulfillment_error == str(error)
        assert p.processing_owner is None
        assert BotEvent.query.count() == 0
