#!/bin/bash
# Bootstrap an ITG Xray Panel production deployment.
#
# Downloads the prod docker-compose, Caddy config and .env template, then
# generates a fresh .env with strong random secrets on first run. Existing
# .env is preserved — re-running just refreshes the supporting files.
#
# Bot configuration (token, admin IDs, YooKassa keys, timezone) lives in the
# panel UI now — no YAML required. The bot service token is the only thing
# you write back to .env; everything else is set under Bot → Settings.

set -e

REPO_URL="https://raw.githubusercontent.com/IvanTopGaming/ITG_xray_panel/main"
PROJECT_DIR="ITG_xray_panel"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}ITG Xray Panel — production installer${NC}"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

download_file() {
    local remote_path=$1 local_path=$2
    mkdir -p "$(dirname "$local_path")"
    echo -n "  $local_path … "
    if curl -fsSL "$REPO_URL/$remote_path" -o "$local_path"; then
        echo -e "${GREEN}OK${NC}"
    else
        echo "FAIL"; exit 1
    fi
}

gen_secret() {
    python3 -c "import secrets; print(secrets.token_urlsafe($1))" 2>/dev/null \
        || head -c 64 /dev/urandom | base64 | tr -d '/+=\n' | head -c "$1"
}

echo "Downloading deployment files..."
download_file "docker-compose.prod.yml" "docker-compose.yml"
download_file "caddy/caddy.json" "caddy/caddy.json"
download_file "scripts/generate_certs.sh" "scripts/generate_certs.sh"
download_file ".env.example" ".env.example"
chmod +x scripts/generate_certs.sh

if [ -f .env ]; then
    echo -e "${YELLOW}.env exists — keeping it.${NC}"
else
    PANEL_SECRET_PATH=$(gen_secret 12)
    SECRET_KEY=$(gen_secret 48)
    PANEL_ADMIN_PASSWORD=$(gen_secret 16)
    cat > .env <<EOF
# Pin these to the versions you want to deploy. Bumps to versions.json on
# main automatically build + push corresponding images to GHCR.
XRAY_IMAGE=ghcr.io/xtls/xray-core:latest
SOCKET_PROXY_IMAGE=tecnativa/docker-socket-proxy:latest
REDIS_IMAGE=redis:7.4-alpine
BACKEND_IMAGE=ghcr.io/ivantopgaming/panel-backend:v2.0.0
FRONTEND_IMAGE=ghcr.io/ivantopgaming/panel-frontend:v2.0.0
CADDY_IMAGE=ghcr.io/ivantopgaming/panel-caddy:v1.0.2
BOT_IMAGE=ghcr.io/ivantopgaming/panel-bot:v2.0.0

# REQUIRED — edit before first start.
PANEL_DOMAIN=panel.example.com
PROXY_DOMAIN=www.google.com

# Generated by this installer (already strong randoms — keep them safe).
PANEL_SECRET_PATH=$PANEL_SECRET_PATH
SECRET_KEY=$SECRET_KEY
PANEL_ADMIN_USER=admin
PANEL_ADMIN_PASSWORD=$PANEL_ADMIN_PASSWORD

CORS_ORIGINS=https://panel.example.com
RATELIMIT_STORAGE_URI=redis://redis:6379/0

# Proxy for the bot's outbound Telegram traffic. Empty = direct.
TELEGRAM_PROXY_URL=

# Bot service token — fill after first panel start (Bot → Settings →
# Rotate token), then: docker compose up -d bot
BOT_SERVICE_TOKEN=
EOF
    echo
    echo -e "${GREEN}.env generated.${NC}"
    echo -e "${YELLOW}Admin password:${NC} $PANEL_ADMIN_PASSWORD"
    echo -e "${YELLOW}Secret path:${NC}    /$PANEL_SECRET_PATH/"
    echo "Save them somewhere safe — they're random and only shown once."
fi

cat <<EOM

${GREEN}Done.${NC} Next steps:
  1. Edit .env — set PANEL_DOMAIN and CORS_ORIGINS to your real domain.
  2. docker compose pull
  3. docker compose up -d backend frontend caddy redis xray socket-proxy
       (everything except the bot — it needs BOT_SERVICE_TOKEN first)
  4. Open https://<PANEL_DOMAIN>/<PANEL_SECRET_PATH>/, log in as admin.
  5. Panel → Bot → Settings:
       · Rotate BOT_SERVICE_TOKEN → copy the new value into .env
       · Set bot_token, admin Telegram IDs, timezone
       · (Optional) Set YooKassa shop_id + secret_key for paid checkout
  6. docker compose up -d bot
  7. docker compose logs -f backend bot
EOM
